import { MigrationInterface, QueryRunner } from 'typeorm';
export class Initial1780000000000 implements MigrationInterface {
  async up(q: QueryRunner): Promise<void> {
    await q.query(`CREATE EXTENSION IF NOT EXISTS btree_gist;
CREATE TABLE propietarios (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
tipo_titular text NOT NULL,
nombre text NOT NULL,
documento text NOT NULL,
direccion text NOT NULL,
telefono text NOT NULL,
email text NOT NULL);
CREATE TABLE administradores (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
propietario_id integer NOT NULL REFERENCES propietarios(id),
auth_user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id),
nombre text NOT NULL,
apellido text NOT NULL,
email text NOT NULL,
rol text NOT NULL);
CREATE TABLE clientes (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
auth_user_id uuid NOT NULL UNIQUE REFERENCES auth.users(id),
nombre text NOT NULL,
apellido text NOT NULL,
documento text NOT NULL,
email text NOT NULL,
telefono text NOT NULL,
fecha_nacimiento date NOT NULL);
CREATE TABLE propiedades (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
propietario_id integer NOT NULL REFERENCES propietarios(id),
nombre text NOT NULL,
tipo text NOT NULL,
descripcion text NOT NULL,
direccion text NOT NULL,
latitud numeric(10,7) NOT NULL,
longitud numeric(10,7) NOT NULL,
capacidad integer NOT NULL,
cantidad_habitaciones integer NOT NULL,
cantidad_banos integer NOT NULL,
hora_checkin time NOT NULL,
hora_checkout time NOT NULL,
acepta_mascotas boolean NOT NULL,
acepta_menores boolean NOT NULL,
limite_meses_reserva integer NOT NULL,
precio_noche numeric(14,2) NOT NULL,
porcentaje_sena numeric(14,2) NOT NULL,
estado text NOT NULL);
CREATE TABLE imagenes_propiedad (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
propiedad_id integer NOT NULL REFERENCES propiedades(id),
url text NOT NULL,
orden integer NOT NULL,
storage_path text );
CREATE TABLE reservas (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
propiedad_id integer NOT NULL REFERENCES propiedades(id),
cliente_id integer NOT NULL REFERENCES clientes(id),
fecha_desde date NOT NULL,
fecha_hasta date NOT NULL,
fecha_creacion timestamptz NOT NULL,
fecha_vencimiento_temporal timestamptz NOT NULL,
cantidad_huespedes integer NOT NULL,
estado text NOT NULL,
importe_total numeric(14,2) NOT NULL,
importe_sena numeric(14,2) NOT NULL);
CREATE TABLE periodos_bloqueados (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
propiedad_id integer NOT NULL REFERENCES propiedades(id),
fecha_desde date NOT NULL,
fecha_hasta date NOT NULL,
motivo text NOT NULL);
CREATE TABLE pagos (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
reserva_id integer NOT NULL REFERENCES reservas(id),
monto numeric(14,2) NOT NULL,
fecha timestamptz NOT NULL,
estado text NOT NULL,
id_transaccion_externa text NOT NULL);
CREATE TABLE cancelaciones (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
reserva_id integer NOT NULL REFERENCES reservas(id),
administrador_id integer  REFERENCES administradores(id),
cliente_id integer  REFERENCES clientes(id),
tipo_usuario text NOT NULL,
fecha timestamptz NOT NULL,
motivo text NOT NULL,
es_excepcional boolean NOT NULL,
requiere_reintegro boolean NOT NULL);
CREATE TABLE email_outbox (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
event_id uuid NOT NULL,
topic text NOT NULL,
payload jsonb NOT NULL,
created_at timestamptz NOT NULL,
published_at timestamptz );
CREATE TABLE email_receipts (id integer GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
event_id uuid NOT NULL,
sent_at timestamptz NOT NULL);

ALTER TABLE propietarios ADD CONSTRAINT propietario_documento_unique UNIQUE(documento);
ALTER TABLE clientes ADD CONSTRAINT cliente_documento_unique UNIQUE(documento), ADD CONSTRAINT cliente_email_unique UNIQUE(email);
ALTER TABLE administradores ADD CONSTRAINT admin_email_unique UNIQUE(email), ADD CONSTRAINT admin_rol CHECK(rol IN ('titular','empleado'));
ALTER TABLE propiedades ADD CONSTRAINT propiedad_valida CHECK(capacidad>0 AND cantidad_habitaciones>=0 AND cantidad_banos>0 AND precio_noche>0 AND porcentaje_sena>0 AND porcentaje_sena<=100 AND limite_meses_reserva BETWEEN 1 AND 36 AND latitud BETWEEN -90 AND 90 AND longitud BETWEEN -180 AND 180 AND estado IN ('ACTIVA','INACTIVA'));
ALTER TABLE reservas ADD CONSTRAINT reserva_fechas CHECK(fecha_desde<fecha_hasta), ADD CONSTRAINT reserva_valida CHECK(cantidad_huespedes>0 AND importe_total>0 AND importe_sena>0 AND importe_sena<=importe_total AND estado IN ('TEMPORAL','CONFIRMADA','VENCIDA','CANCELADA'));
ALTER TABLE reservas ADD CONSTRAINT reservas_no_superpuestas EXCLUDE USING gist(propiedad_id WITH =, daterange(fecha_desde,fecha_hasta,'[)') WITH &&) WHERE(estado IN ('TEMPORAL','CONFIRMADA'));
ALTER TABLE periodos_bloqueados ADD CONSTRAINT bloqueo_fechas CHECK(fecha_desde<fecha_hasta);
ALTER TABLE pagos ADD CONSTRAINT pago_transaccion UNIQUE(id_transaccion_externa), ADD CONSTRAINT pago_valido CHECK(monto>0 AND estado IN ('PENDIENTE','APROBADO','RECHAZADO','CANCELADO'));
ALTER TABLE cancelaciones ADD CONSTRAINT cancelacion_reserva UNIQUE(reserva_id), ADD CONSTRAINT cancelacion_actor CHECK((administrador_id IS NOT NULL AND cliente_id IS NULL AND tipo_usuario='ADMINISTRADOR') OR (administrador_id IS NULL AND cliente_id IS NOT NULL AND tipo_usuario='CLIENTE'));
ALTER TABLE email_outbox ADD CONSTRAINT outbox_event_unique UNIQUE(event_id);
ALTER TABLE email_receipts ADD CONSTRAINT receipt_event_unique UNIQUE(event_id);
CREATE INDEX ON reservas(propiedad_id); CREATE INDEX ON reservas(cliente_id); CREATE INDEX ON reservas(estado); CREATE INDEX ON reservas(fecha_desde,fecha_hasta);
CREATE INDEX ON periodos_bloqueados(propiedad_id); CREATE INDEX ON pagos(reserva_id); CREATE INDEX ON propiedades(propietario_id); CREATE INDEX ON email_outbox(created_at) WHERE published_at IS NULL;
ALTER TABLE propietarios ENABLE ROW LEVEL SECURITY; REVOKE ALL ON propietarios FROM anon, authenticated;
ALTER TABLE administradores ENABLE ROW LEVEL SECURITY; REVOKE ALL ON administradores FROM anon, authenticated;
ALTER TABLE clientes ENABLE ROW LEVEL SECURITY; REVOKE ALL ON clientes FROM anon, authenticated;
ALTER TABLE propiedades ENABLE ROW LEVEL SECURITY; REVOKE ALL ON propiedades FROM anon, authenticated;
ALTER TABLE imagenes_propiedad ENABLE ROW LEVEL SECURITY; REVOKE ALL ON imagenes_propiedad FROM anon, authenticated;
ALTER TABLE reservas ENABLE ROW LEVEL SECURITY; REVOKE ALL ON reservas FROM anon, authenticated;
ALTER TABLE periodos_bloqueados ENABLE ROW LEVEL SECURITY; REVOKE ALL ON periodos_bloqueados FROM anon, authenticated;
ALTER TABLE pagos ENABLE ROW LEVEL SECURITY; REVOKE ALL ON pagos FROM anon, authenticated;
ALTER TABLE cancelaciones ENABLE ROW LEVEL SECURITY; REVOKE ALL ON cancelaciones FROM anon, authenticated;
ALTER TABLE email_outbox ENABLE ROW LEVEL SECURITY; REVOKE ALL ON email_outbox FROM anon, authenticated;
ALTER TABLE email_receipts ENABLE ROW LEVEL SECURITY; REVOKE ALL ON email_receipts FROM anon, authenticated;
`);
  }
  async down(q: QueryRunner): Promise<void> {
    await q.query(
      `DROP TABLE email_receipts,email_outbox,cancelaciones,pagos,periodos_bloqueados,reservas,imagenes_propiedad,propiedades,clientes,administradores,propietarios CASCADE;`,
    );
  }
}
